### PR TITLE
Better repo structure

### PR DESCRIPTION
**Pull request by neysofu**
This is the first of a series of PRs that will improve the folder structure and file exploration in the repository.

- Added a very basic README, which licensing information and a link to the public GIP.
- Created a Cargo workspace with `rust-toolchain.toml` support, so everybody uses the same version of `rustc`.
- Moved all Rust code into `crates/`. Next, I'd like to bring `packages/contracts` and `packages/subgraph` to the root directory of the project.

This PR depends on https://github.com/edgeandnode/block-oracle/pull/45. Let's ,erge that first!

### CODE REVIEW

**Comment by neysofu** [comment]
Let me fix the branch history before reviewing.

**Comment by neysofu** [comment]
Fixed!

**Review by tilacog — APPROVED** [review]

**Comment by tilacog** [comment]
Not sure if I should merge my other PRs after or before this one

**Comment by neysofu** [comment]
> Not sure. I can either rebase and merge after you, or you can cherry-pick your commits on top of this. Your call

**Comment by tilacog** [comment]
Let's rebase this one on top of the latest `main`, then I can rebase #43 and #39 on top of this

**Comment by neysofu** [comment]
Rebased. Can I merge? @tilacog

**Comment by tilacog** [comment]
Sure, go ahead

**Pull request merged**
